const SETTOKEN = 'SETTOKEN';
const SETLOADING = 'SETLOADING';
const SETERROR = 'SETERROR';
const SETISAUTH = 'SETISAUTH';
const SETISREGISTER = 'SETISREGISTER';


export {SETERROR, SETTOKEN,SETISAUTH,SETLOADING,SETISREGISTER}